// Deterministic seeded pseudo-random — same seed always produces same sequence
function seededRand(seed: string, min: number, max: number): number {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  const norm = Math.abs(h) / 2147483648;
  return Math.floor(norm * (max - min + 1)) + min;
}

// ─── TIER 1 — HIGH SCORE (score >= 85) ───────────────────────────────────────
// Short, flat, matter-of-fact. No gender pronouns. No strong claims or recommendations.
export const COMMENTS_HIGH: string[] = [
  "Ran our Atlanta-to-Memphis lane for about 8 months. No late deliveries, PODs always in on time. No issues.",
  "Handled a reefer load through a winter storm and still made the window. Sent updates when needed.",
  "Used on our produce runs out of Salinas. Load counts were accurate, no shortage claims.",
  "Good driver. Kept the truck clean, no write-ups from receivers, communication was fine.",
  "Ran dry van out of Chicago for two seasons. Paperwork always in order, detention time was low.",
  "Had this driver on flatbed for about five months. No load shifts, no damage claims. Dock crews were fine with it.",
  "Used on overnight LTL runs. Always checked in, never a no-call. Fuel card usage was clean.",
  "Ran a reefer lane for almost a year. Temperature logs accurate, no product loss.",
  "Pre-trip reports always submitted before departure. Three DOT reviews, no findings.",
  "Handled a pharmacy distribution lane for six months. Window compliance above our fleet average.",
  "Used on produce runs from the Central Valley. Load counts matched every time. Showed up prepped.",
  "Ran intermodal port pickups. Paperwork complete, no holds on cargo.",
  "Covered a dedicated account on short notice. Customer didn't flag anything.",
  "Ran flatbed twice a week for three months. No damage, receivers gave thumbs up.",
  "Drove between two distribution centers. Timing consistent, called ahead on traffic delays.",
  "Safety director reviewed the logs. Zero HOS violations, no discrepancies over a full year.",
  "Ran produce reefer out of Nogales. Temperature compliance was solid across 22 loads.",
  "Drove dry van through the Midwest for most of last year. No no-shows from this driver.",
  "Covered our Southeast corridor for 14 months. On-time delivery rate was in the high 90s.",
  "Ran drop-and-hook at three distribution centers. Cycle times were fast, trailers inspected correctly.",
  "Had this driver on hazmat loads. Proper placarding, paperwork complete. No issues at weigh stations.",
  "Ran LTL consolidation pickups for two quarters. Load sequencing correct, no missed stops.",
  "Ran overnight refrigerated lane between two plants. No temp excursions over six months.",
  "Used on automotive parts — time-sensitive windows. Made every appointment across 18 loads.",
  "Had this driver on flatbed steel hauls. Chains inspected at 50-mile mark. Clean load record.",
  "Drove tanker for four months. No spills, valve checks done, paperwork complete.",
  "Ran regional routes for about 10 months. No accidents, no complaints from shippers or receivers.",
  "Had this driver on a hazardous materials route. Placard compliance was clean, no roadside issues.",
  "Used on a new lane for two months. No problems. Helped us verify the lane was workable.",
  "Ran overnight consolidation five nights a week. Attendance was solid for four months.",
  "Ran food-grade tank. Cleaning logs complete, no contamination incidents, generally on time.",
  "Covered for our regular driver on short notice three times. Performed fine each time.",
  "Ran a retail distribution loop — 14 stops, mixed freight. Delivery accuracy was solid.",
  "Ran flatbed container moves. No dropped chassis, documentation correct before departure.",
  "Covered seasonal agricultural run for two harvests. No issues either year.",
  "Drove refrigerated van in a city environment. Tight windows, handled it without issues.",
  "Ran regional dry van. Mileage log accurate, no fuel disputes, no complaints.",
  "Ran the overnight relay for six months. Handoffs on schedule, equipment in good shape.",
  "Had this driver on a flatbed lumber delivery. Load counts matched. No citations.",
  "Drove beverage distribution — heavy freight, multiple stops. Load counts matched, no damages.",
  "Ran bulk dry freight. Documentation accurate, no overweight issues, weigh stations clean.",
  "Had this driver on construction materials. No load shift incidents, tie-down logs complete.",
  "Drove a coast-to-coast relay for six months. Handoffs on schedule, consistent.",
  "Ran flatbed out of our steel service center. Load weights correct, no overweight citations.",
  "Used on our container chassis circuit. Yard compliance correct, no lost chassis incidents.",
  "Ran hazmat dry van — Class 3. Placarding correct, paperwork clean, no spills.",
  "Had this driver on a steel coil run. Cradles and binders correct, no coil movement at checkpoints.",
  "Ran import container drayage. Port gate efficiency fine, no container damage.",
  "Had this driver on specialty freight — glass panels. No damage claims across 16 loads.",
  "Ran trade show freight — penalty-heavy windows. No late deliveries across two seasons.",
  "Drove our fresh-cut flower reefer lane. Temperature was exact throughout.",
  "Had this driver on bulk liquid tanker runs. No spills, no valve issues, proper pre-trip.",
  "Ran hospital supply chain delivery. No late deliveries, no damaged goods, documentation complete.",
  "Drove postal contract freight. Scan compliance high, delivery sequencing correct.",
  "Used on auto parts express. No assembly line stoppage events traced to this driver.",
  "Ran daily newspaper distribution run. Pre-dawn start, tight timing. Attendance was solid.",
  "Ran fuel tanker. Meter calibration checks done, no short delivery claims, loading smooth.",
  "Had this driver on building materials flatbed. Proper securement every time, no citations.",
  "Ran frozen food distribution. Reefer settings confirmed before departure, no claims.",
  "Had this driver on bulk feed haul. Scale tickets matched, no citation at the scales.",
  "Drove food service distribution route in an urban environment. No complaints from customers.",
  "Had this driver on oversized wind turbine transport. Escort coordination correct, no violations.",
  "Ran medical equipment delivery — fragile freight. No damage, no documentation gaps.",
  "Drove our interplant shuttle at high frequency. Never missed a scheduled run in four months.",
  "Had this driver on specialty gas cylinder delivery. Cylinder counts matched every delivery.",
  "Ran cross-dock. Sort speed fine, load accuracy correct, no mis-ships.",
  "Used on a military base delivery contract. Security compliance correct, no access issues.",
  "Ran regional LTL out of our hub. Sort accuracy high, no misdirected freight.",
  "Had this driver on our high-value electronics freight lane. Chain of custody documentation correct.",
  "Ran regional courier circuit. On time on the vast majority of deliveries.",
  "Drove our morning fresh delivery route. Generally on time, no shortage disputes.",
  "Used on construction site delivery. All loads intact. Occasional sign-in reminder needed.",
  "Ran seasonal produce lane. Solid performance through core of harvest.",
  "Had this driver on bulk plastic pellet pneumatic. No contamination, delivery volumes matched.",
  "Drove pharmaceutical last mile. Chain of custody documentation intact throughout.",
  "Ran our dedicated grocery account. Receiver feedback was generally positive.",
  "Used on a flatbed event freight run. Staging correct, no client issues.",
  "Had this driver on hazmat — compliance correct on every load. No inspection flags.",
  "Ran our temperature-controlled pharmaceutical. Documentation complete, no excursions.",
  "Drove retail chain distribution route. Consistent timing, no charge-backs.",
  "Had this driver on our food-grade tanker. Cleaning logs complete, no complaints.",
  "Ran our overnight tractor-trailer relay. Swaps on time, truck fueled and logged correctly.",
  "Used on port-to-warehouse drayage. No demurrage charges traced to this driver.",
  "Ran LTL out of our regional hub. Delivery accuracy high throughout the contract.",
  "Had this driver on a flatbed oversize run. Permit handling correct, no enforcement stops.",
  "Ran chemical tanker route. Rinsing logs complete, material safety documentation correct.",
  "Drove daily produce shuttle between packing shed and distribution center. Fast load times.",
  "Ran overnight team driving. Rest compliance correct, logbooks matched, no disputes.",
  "Had this driver on our high-cube trailer operations. No product damage from improper stacking.",
  "Drove flatbed lumber route. Load configuration correct, no load shifts at checkpoints.",
  "Ran our LTL pickup routes in a metro area. Efficient navigation, no missed businesses.",
  "Had this driver on our retail seasonal push. Managed the schedule without constant oversight.",
  "Ran our daily warehouse-to-warehouse shuttle for six months. Zero incidents.",
  "Drove our regional evening freight run. Generally on schedule, no escalations.",
  "Had this driver on flatbed agricultural loads. Tarp coverage correct, freight undamaged.",
  "Ran container pickup circuit for a month. Handled terminal navigation without issues.",
  "Used on a short-haul city delivery operation. Customer satisfaction was fine.",
  "Had this driver on overnight reefer on a regular lane. Temps were correct, no issues.",
  "Ran our LTL consolidation circuit. Delivery accuracy was above average for the contract.",
  "Used on a specialty cargo run. Load restraint was correct, no freight damage.",
];

// ─── TIER 2 — AVERAGE SCORE (score 70–84) ────────────────────────────────────
// Neutral, honest. One minor issue per comment. No dramatic language.
export const COMMENTS_MID: string[] = [
  "Decent overall. Had to follow up a couple times for PODs but loads got delivered.",
  "Ran fine most of the time. Showed up late to the receiver once and didn't call ahead. Otherwise no complaints.",
  "One situation at a dock where things took longer than expected. Nothing went wrong but it held up the schedule.",
  "Paperwork needs reminders sometimes. We've gotten used to following up before end of day to get load confirmation.",
  "Usually on time. Had one trip where we didn't hear anything for a few hours mid-route. Everything turned out fine.",
  "Good attitude when you talk to the driver. A bit hard to reach by phone sometimes.",
  "Did the job. One minor backing incident in a crowded lot — no damage, took a while to sort out.",
  "Fine on standard lanes. One overnight haul ran into schedule issues that took a couple trips to sort out.",
  "Fuel card showed a small overage last quarter. Couldn't confirm if it was a pump authorization glitch or something else.",
  "Gets the freight there. Pre-trip reports were submitted late a few times before we said something.",
  "Average on our metrics. One brief exchange with a receiver about detention time — resolved quickly.",
  "Had one HOS discrepancy on a long-haul run. Said it was a logging mistake. We couldn't confirm either way.",
  "Cab was left messy at a truck swap once. Previous driver flagged it. Minor but noted.",
  "Communication during runs could be better. We usually have to initiate contact rather than getting check-ins.",
  "One stop got skipped and came back saying the address was wrong. We verified — address was correct.",
  "Fine on familiar lanes. Put on a new route and called dispatch four times for directions.",
  "Had to remind about submitting mileage reports twice. Not a big issue but adds overhead.",
  "Ran the afternoon shift for a month. A couple late check-ins, nothing that caused a delivery failure.",
  "One pre-trip report had a brake light listed as functional that wasn't — caught by our yard crew.",
  "Temperature was in range but toward the edge of spec twice on a reefer run. Adjusted the setpoint after.",
  "Took two weeks to learn the lane, which was longer than expected. After that, consistency was fine.",
  "One situation where the load came in underweight — shorted a pallet. Receiver noticed, we issued a credit.",
  "Generally reliable. Had one no-call during a weather event — turned out there was a signal issue. Understandable.",
  "Fuel efficiency was below fleet average throughout the contract. Not critical but it adds up.",
  "Had one trip where everything went quiet for about four hours mid-route. Everything was fine in the end.",
  "Had this driver on a flatbed route. Re-inspection at the 50-mile mark was done late twice.",
  "On short hauls it's fine. Put on an overnight and arrived 45 minutes outside the window the first time.",
  "Needed a reminder about proper seal documentation on a cross-border load. Got it right after that.",
  "LTL consolidation had one stop with a count discrepancy — three units short. Never fully resolved.",
  "Paperwork got a bit sloppy toward the end of a busy period.",
  "Got pulled into a weigh station and came out with a citation for log entry timing. First one on record with us.",
  "Arrived once without the correct delivery manifest — had to resend it on the road.",
  "One week had three runs with late check-out scans — said the scanner was glitching. IT couldn't confirm.",
  "One load came in with a couple damaged cases at the bottom. Packing at origin was also questionable.",
  "Took significantly longer than expected on two stops, which affected the afternoon schedule.",
  "Had to remind about logging the pre-cool temp before departure once. Didn't happen again.",
  "One week submitted duplicate expense receipts for fuel — looked like a system error.",
  "Failed to close trailer doors fully at a transfer yard once. Crew caught it before departure.",
  "Communication is inconsistent — sometimes proactive, sometimes we have to dig for updates.",
  "Parked in a restricted zone at a delivery stop. Got a warning from the facility.",
  "Tarp coverage was slightly off on one load. Receiver noted it but freight was undamaged.",
  "One chassis mix-up at the terminal caused a 2-hour delay. Got it sorted out without help.",
  "Arrived without the proper load-specific documentation once. Had to email it mid-route.",
  "Requested overtime twice then called out sick both times. Might be coincidence.",
  "One load was sealed incorrectly at origin — should have been caught at pickup.",
  "One night was 30 minutes late to a relay swap point with no call ahead.",
  "Had one misrouting event — took the wrong interchange and added 40 minutes to the run.",
  "One delivery had a missed signature — caused a brief receiver dispute.",
  "One citation for a defective marker light. Pre-trip should have caught it.",
  "ELD syncing was inconsistent on a seasonal contract, which created log review overhead.",
  "Missed one handling note on a shipment with special requirements. No damage but the customer noticed.",
  "Hit most delivery windows. Missed two and didn't call ahead either time.",
  "One instance of improper chain placement — safety supervisor flagged it at pre-departure check.",
  "One delivery was left at the wrong address. Caught by the customer, corrected same day.",
  "Ran medical supply run. One situation where a delay at the shipper wasn't reported promptly.",
  "Two loads where the weight was listed incorrectly on the freight bill — needed corrections.",
  "Rural delivery circuit completed all runs but slower than expected, which backed up the return schedule.",
  "One incorrect trailer hooked at the yard. Caught before departure.",
  "Ran steel service center run. Occasionally slow getting in and out of the yard.",
  "Occasionally slow to update the load tracking system on a cold chain run.",
  "One customer complaint about attitude at a receiver — brief, no follow-up needed.",
  "One cleaning verification log was incomplete on a bulk food-grade haul. Completed when asked.",
  "One load missed the appointment window, which cost us a layover charge.",
  "One week the pre-trip inspection form wasn't submitted for two consecutive days.",
  "One occasion where parking was at an unauthorized facility overnight. No incident.",
  "Reliable on specific days. Communication between runs during the week was slow.",
  "One DOT scale inspection resulted in a minor brake adjustment warning.",
  "Delivery times were loose compared to our standard on a multi-drop circuit.",
  "One container had a broken seal that wasn't noted at pickup.",
  "Fuel expenses one week didn't match the route mileage on an agricultural shuttle.",
  "Customer feedback was neutral throughout. Gets the job done.",
  "One stop had a delay because the driver couldn't locate the receiving bay.",
  "One missed delivery appointment required us to rebook with the receiver on an overnight run.",
  "One complaint from a shipper about how a check-in delay was handled.",
  "Performance was consistent in month one, dipped in month two, recovered by month three.",
  "One placard was placed incorrectly at first on a hazmat dry van. Corrected before departure.",
  "One restaurant reported arrival outside the scheduled window on two visits.",
  "One gap in the temperature log documentation on a pharmaceutical run. Filled in retroactively.",
  "On-time rate was around 85% over the contract. Acceptable, not great.",
  "One late swap required us to call the receiving driver on an overnight relay.",
  "Occasionally needed reminders about signing in at construction delivery sites.",
  "One pump seal check was skipped on a delivery. Found on the post-trip report.",
  "Ran dedicated grocery account. One week had three late arrivals — attributed to a reroute.",
  "One piece of equipment was off-spotted at a flatbed event freight delivery. Client noted it.",
  "One chassis was turned in with a damaged landing gear. Unclear when it happened.",
  "One delivery had broken pallet wrap. Appeared to be shipper's packing.",
  "One stint where an incorrect trailer number was picked up at a yard.",
  "One post-delivery rinse log was submitted late. End of a long shift.",
  "One seal number discrepancy on a high-security lane. Resolved after review.",
  "Left a dock once without waiting for full unload confirmation — caused a recount.",
  "On time on 88% of deliveries. Two exceptions due to traffic, one unexplained.",
  "One materials shortage at a stop — appeared to be a shipper issue.",
  "One delivery window was missed by 20 minutes with no call to the client.",
  "One missing signature on a delivery receipt — went back to get it.",
  "One stop had a customer complaint about tone — brief, not escalated.",
  "One container was damaged during terminal handling. Under review.",
  "Three stops marked delivered but signatures didn't match the addresses. Still unresolved.",
  "One delivery had a paperwork error that resulted in a regulatory notice.",
  "One fuel card transaction flagged at a location outside the normal route.",
];

// ─── TIER 3 — LOW SCORE (score < 70) ─────────────────────────────────────────
// Direct, disappointed. 1–2 specific problems. Still no strong accusations.
export const COMMENTS_LOW: string[] = [
  "Had this driver on two loads. First one was fine. Second one went dark for hours and freight was delivered late. Lost a client over it.",
  "Showed up to a flatbed pickup without straps or tarps. Had to delay the shipper 3 hours.",
  "Got a call from our receiver saying there was an argument at the dock over detention time. We don't need that kind of friction.",
  "Load was abandoned mid-route citing a personal emergency. Freight sat 14 hours. No advance notice.",
  "Adjusted the reefer temperature without authorization. Product arrived above spec. Customer refused the load.",
  "Three late deliveries in a row on the same lane. After the third one we ended the arrangement.",
  "Failed a roadside inspection — logbook was 90 minutes off. OOS until a compliant restart.",
  "Went unreachable for almost a full shift. Turned the ELD off at some point. Found the truck at a truck stop.",
  "Missed two stops on an LTL run and said time ran out. Didn't call. Recipients had to wait until next day.",
  "Showed up at a food-grade facility without the required wash certificate. Missed the appointment and the pickup slot.",
  "Fuel receipts didn't match the route. The numbers didn't add up and there was no clear explanation.",
  "Brake citation at a weigh station — out-of-service order. Pre-trip should have caught it. Freight sat two days.",
  "First week was fine. Second week stopped checking in and deliveries were 60-90 minutes late every day.",
  "Missed the appointment window on a time-critical pharmaceutical load by 4 hours. No update until we called the receiver.",
  "A steel coil shifted in transit — cradle wasn't properly secured. Load had to be re-secured roadside.",
  "A verbal altercation with a shipper's loading crew got reported to management. Had to remove from that account.",
  "Ran a relay and was supposed to swap at 2 AM. Didn't show until 6 AM with no call. Threw off two drivers' schedules.",
  "Incorrect placards were placed on a hazmat trailer. We caught it before departure but it shouldn't happen.",
  "Left a dock without waiting for the load count to be confirmed. Three units came up short at delivery.",
  "Got a speeding citation — 18 over in a 65. That's a liability issue for us.",
  "Dropped the wrong container at the wrong yard. Cost 4 hours and a demurrage fee.",
  "Drove past a DOT weigh station without stopping. We got the notice two weeks later.",
  "Late to the shipper on three out of four loads. Different excuse each time.",
  "Reefer was found turned off during a run. No explanation given.",
  "Backed into another trailer at a truck stop. Didn't report it until we asked about a new dent.",
  "Refused a randomly selected drug test citing a scheduling conflict.",
  "Showed up 2 hours late to the shipper, missed the loading window, and the shipper reassigned the freight.",
  "Two no-shows on Monday mornings. No call either time until we tracked the driver down.",
  "Minor at-fault accident — rear-ended a vehicle in a construction zone at low speed.",
  "Multiple delivery exceptions on LTL work — wrong addresses logged, parcels left in wrong locations.",
  "Called in sick four times in six weeks. Coverage cost more than the loads delivered.",
  "Arrived 6 hours past the cold-chain window on a pharmaceutical load. Product was unusable.",
  "Argued with our safety coordinator about logbook hours. Records showed a 13-hour driving day.",
  "Missed a delivery window by over 3 hours on an overnight run. Safety concern raised.",
  "Post-delivery rinse wasn't done on a chemical tanker. Next load got contaminated.",
  "Disappeared mid-route for 8 hours. Cell off, ELD unplugged.",
  "Two cartons were missing on delivery and the seal was broken. Investigation went nowhere.",
  "Unhooked the wrong trailer at a yard and drove off with another carrier's loaded trailer.",
  "Citation for operating with a defective brake. Should show up on a pre-trip.",
  "DOT physical renewal window missed while still driving. Found out on a compliance check.",
  "Client called saying the driver was rude to their receiving manager. We had to respond.",
  "One load went undelivered because the receiver was supposedly closed. Receiver says nobody showed up.",
  "Log falsification — an auditor found a discrepancy between paper log and ELD data.",
  "Load arrived with significant chilling damage. No temp log available.",
  "Two loads had shortage claims from receivers. Counts didn't match at pickup either, which wasn't documented.",
  "Moving violation for running a red light in a commercial vehicle.",
  "Didn't tarp a load citing it wasn't wet freight. The freight was outdoor building materials — tarping was required.",
  "Abandoned a refrigerated trailer at a rest area. Didn't call road service.",
  "Minor dock accident — clipped the bumper while pulling out. Damage was about $1,400.",
  "Missed a delivery appointment to a pharmacy that had a scheduled drug shipment.",
  "Removed from a dedicated retail account after the client complained about multiple late deliveries.",
  "Emergency equipment wasn't properly stocked on a hazmat dry van.",
  "Dropped a container off-spot at a terminal. Caused a significant delay in processing.",
  "Disabled the reefer alarm when the unit faulted. Didn't report it. Product was lost.",
  "Told us the receiver had refused the load. We called the receiver — they said nobody had shown up.",
  "Delivered to the wrong city. Misread the delivery order and didn't verify before departure.",
  "Two separate incidents reported at different dock locations in the same week.",
  "Four late deliveries in one week on a lane that had been running smoothly for two months.",
  "IFTA discrepancy across three states. The paperwork didn't support the mileage claims.",
  "Ran through a regulated corridor without the required oversize permit.",
  "Three delivery shortage claims in one week — 19 units total unaccounted for.",
  "High-value load arrived with a broken seal. No explanation for when it occurred.",
  "Called out sick on a critical shipment day — no backup available. Lost a client relationship.",
  "Delivered without the required temperature log on a regulated freight lane.",
  "Two nights in a row, items were left off the truck that were scanned as loaded. Both required redelivery.",
  "Client escalated twice in three weeks. Both times the issue was communication during a delay.",
  "Moving violation — failure to obey a traffic control device in a commercial vehicle.",
  "Incorrect post-delivery documentation three times in one month. Product reconciliation became a problem.",
  "Freight arrived damaged — a pallet had clearly been dragged rather than hand-trucked. Receiver refused it.",
  "Called out five times in eight weeks during a peak season contract.",
  "Load arrived warm on a produce run. Reefer was set wrong at pickup and it wasn't caught.",
  "Two separate backing incidents at receivers in the same month. Minor damage both times.",
  "Two loads had improper weight distribution. Weigh station flagged both.",
  "Left dock before unload was confirmed several times. Kept finding issues afterward.",
  "Pulled from a route after mentioning to another driver that sleep was an issue.",
  "Cross-contamination risk on a food-grade tanker after an incomplete cleaning.",
  "Load restraint was improperly configured on a specialty cargo run.",
  "Three check-in no-shows in a single week.",
  "Two deliveries to a closed facility without contacting us — just drove back with the load.",
  "Consistently ran over ETA by 20-40 minutes without explanation. The client noticed.",
  "Roll-over on a county road. Investigation determined speed was a factor.",
  "Container damaged during terminal handling — forklift damage while the driver was operating.",
  "Three stops marked delivered but signatures didn't match the addresses.",
  "One chemical delivery had a paperwork error that resulted in a regulatory notice.",
  "Fuel card transaction at a location 80 miles outside the route. Couldn't explain it.",
  "Flatbed load securement failed inspection. Freight had to be re-secured on the side of the road.",
  "Load straps were lent to a customer. Found out at the next pickup when there were none on the truck.",
  "Unreachable for 11 straight hours on a time-sensitive load.",
  "Showed up four hours late to a shipper during harvest. Shipper told us not to send this driver back.",
  "Didn't show up to the terminal on the third night of an overnight reefer contract. No replacement available until morning.",
  "Two separate disputes with receiver staff at two different accounts in the same week.",
  "Container was marked as pulled but was still at the terminal 12 hours later.",
  "Attempted to cross a weight-restricted bridge on a heavy haul run.",
  "Following too closely citation — witnessed by an enforcement officer.",
  "Caught on a facility camera using a cell phone while driving on a dedicated client site. Client ended the contract.",
  "Arrived without blocking and bracing materials for a specialized open-deck run. Shipper refused to load.",
  "Showed up on the wrong day for a delivery appointment.",
  "Entered incorrect temperature settings for the return leg on a pharmaceutical cold chain. Load was compromised.",
];

// ─── Carrier pool ─────────────────────────────────────────────────────────────
export const CARRIER_POOL: string[] = [
  "Apex Logistics LLC","Blue Ridge Freight","Ironclad Carriers","Summit Transport Group",
  "RoadStar LLC","Tri-State Haulers","Evergreen Trucking","CrossCountry Freight",
  "Keystone Haulage Inc.","Pacific Rim Transport","Heartland Carriers","Delta Road Inc.",
  "NorthStar Freight","Gulf Coast Logistics","Cascade Trucking Co.","Redline Express",
  "Vanguard Transport","Central States Haulage","Eagle Freight LLC","Atlas Carriers",
  "Beacon Transport Inc.","Continental Freight","Horizon Carriers LLC","Liberty Haulage",
  "Patriot Transport","Premier Freight Group","Titan Trucking","United Carriers",
  "Velocity Freight","Westgate Transport","Alliance Logistics","Blue Diamond Freight",
  "Coastal Express Inc.","Diamond Transport LLC","Empire Carriers","Frontier Freight",
  "Golden Gate Haulage","Harbor Trucking Co.","Interstate Logistics","Junction Freight",
  "Lone Star Transport","Mountain West Carriers","National Freight Inc.","Oak Hill Logistics",
  "Pinnacle Transport","Quality Carriers Inc.","Rainbow Freight","Streamline Transport",
  "Thunder Road Logistics","Union Freight","Valley Transport LLC","Wolverine Carriers",
  "Xpress Freight Inc.","Yankee Haulers","Zenith Transport","Ace Logistics",
  "Buckeye Freight","Capital Carriers","Durable Transport Inc.","Eastern Seaboard Freight",
  "Freedom Logistics","Grand Trunk Carriers","Heritage Transport","Iron Horse Freight",
  "Jersey Haulage","Kings Road Transport","Lakefront Logistics","Metro Carriers LLC",
  "Nova Freight Inc.","Olympian Transport","Platinum Logistics","Quicksilver Freight",
  "Reliable Carriers LLC","Sierra Trucking","Trailblazer Freight","Unified Transport",
  "Viking Carriers Inc.","Weatherford Logistics","Xcaliber Freight","Yellowstone Transport",
  "Zodiac Carriers","Advanced Freight LLC","Bridgeport Logistics","Crown Carriers Inc.",
  "Dynamo Transport","Emerald Freight","Falcon Carriers LLC","Galaxy Logistics",
  "Highpoint Transport","Inland Freight Inc.","Jade Carriers","Kingsley Transport",
  "Lightning Logistics","Meridian Freight","Nexus Carriers","Onyx Transport LLC",
  "Prestige Freight","Quest Logistics Inc.","Raven Carriers","Sapphire Transport",
  "Torchlight Freight","Ultimate Logistics","Valiant Transport LLC","Wildfire Carriers",
  "Sunbelt Carriers Inc.","Lakewood Transport Group","Bluewater Freight","Ridgeline Transport",
  "Stonegate Carriers","Clearwater Logistics","Fieldstone Freight","Cedarwood Transport",
  "Rustic Trail Carriers","Highline Freight LLC","Crosswind Transport","Bridgewater Carriers",
  "Silverline Logistics","Northgate Freight","Southland Carriers","Eastway Transport",
  "Westbrook Freight","Millstone Transport","Irongate Carriers","Brookfield Logistics",
  "Crestview Freight","Harborview Transport","Bayshore Carriers","Tidewater Freight LLC",
  "Ridgecrest Logistics","Pinecrest Transport","Maplewood Carriers","Elmwood Freight",
  "Oakridge Transport","Birchwood Logistics","Cypress Freight Inc.","Magnolia Carriers",
  "Willowbrook Transport","Sycamore Freight","Cottonwood Logistics","Aspen Carriers LLC",
];

// ─── Pick N distinct items deterministically ──────────────────────────────────
export function pickDistinctSeeded<T>(arr: T[], count: number, seed: string): T[] {
  const indices = new Set<number>();
  let attempt = 0;
  while (indices.size < count && attempt < count * 40) {
    indices.add(seededRand(seed + 'pk' + attempt++, 0, arr.length - 1));
  }
  return [...indices].slice(0, count).map(i => arr[i]);
}

// ─── Select comments for a driver ────────────────────────────────────────────
export function selectDriverComments(
  driverId: string,
  score: number,
  count: number
): { company_name: string; comment: string; stars: number }[] {
  const pool = score >= 85 ? COMMENTS_HIGH : score >= 70 ? COMMENTS_MID : COMMENTS_LOW;
  const starMin = score >= 85 ? 4 : score >= 70 ? 3 : 1;
  const starMax = score >= 85 ? 5 : score >= 70 ? 4 : 2;

  const comments = pickDistinctSeeded(pool, count, driverId + 'comment');
  const carriers  = pickDistinctSeeded(CARRIER_POOL, count, driverId + 'carrier');

  return comments.map((comment, i) => ({
    company_name: carriers[i] ?? CARRIER_POOL[i % CARRIER_POOL.length],
    comment,
    stars: seededRand(driverId + 'star' + i, starMin, starMax),
  }));
}
